/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.client.ui.settings;

import hr.adinfo.client.ClientAppUtils;
import hr.adinfo.client.datastructures.StaffUserInfo;
import hr.adinfo.client.ui.warehouse.*;
import hr.adinfo.utils.Utils;
import hr.adinfo.utils.Values;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.awt.event.KeyEvent;

/**
 *
 * @author Matej
 */
public class ClientAppSettingsDialog extends javax.swing.JDialog {

	/**
	 * Creates new form ClientAppWarehouseDialog
	 */
	public ClientAppSettingsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		final Window thisWindow = this;
		KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
			@Override
			public boolean dispatchKeyEvent(KeyEvent ke) {
				if(!thisWindow.isDisplayable()){
					KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher(this);
				}
				
				if(!thisWindow.isFocused())
					return false;
				
				if(ke.getID() == KeyEvent.KEY_PRESSED){
					if(ke.getKeyCode() == KeyEvent.VK_ESCAPE){
						jButtonExit.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_F){
						jButtonFiscalisation.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_E){
						jButtonEinvoice.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_P){
						jButtonPrinter.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_N){
						jButtonPaymentMethods.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_U){
						jButtonDiscounts.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_R){
						jButtonLayout.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_K){
						jButtonCashRegister.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_D){
						jButtonWorktime.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_A){
						jButtonAdmin.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_Z){
						jButtonTaxRates.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_T){
						jButtonConsumptionTaxes.doClick();
					} else if(ke.getKeyCode() == KeyEvent.VK_L){
						jButtonImportSettings.doClick();
					}
				}
				
				return false;
			}
		});
		
		// Disable non-admin settings
		if(StaffUserInfo.GetCurrentUserInfo().userRightsType != Values.STAFF_RIGHTS_ADMIN){
			jPanelFiscalisation.setVisible(false);
			jPanelAdminSettings.setVisible(false);
			jPanelTaxes.setVisible(false);
		}
		
		if(StaffUserInfo.GetCurrentUserInfo().userRightsType != Values.STAFF_RIGHTS_ADMIN && StaffUserInfo.GetCurrentUserInfo().userRightsType != Values.STAFF_RIGHTS_OWNER){
			jPanelImportSettings.setVisible(false);
		}
		
		// Setup current user rights
		jButtonPrinter.setVisible(StaffUserInfo.GetCurrentUserInfo().userRights[Values.STAFF_RIGHTS_SETTINGS_PRINTER]);
		jButtonPaymentMethods.setVisible(StaffUserInfo.GetCurrentUserInfo().userRights[Values.STAFF_RIGHTS_SETTINGS_PAYMENTMETHODS]);
		jButtonDiscounts.setVisible(StaffUserInfo.GetCurrentUserInfo().userRights[Values.STAFF_RIGHTS_SETTINGS_DISCOUNTS]);
		jButtonWorktime.setVisible(StaffUserInfo.GetCurrentUserInfo().userRights[Values.STAFF_RIGHTS_SETTINGS_WORKTIMES]);
		jButtonCashRegister.setVisible(StaffUserInfo.GetCurrentUserInfo().userRights[Values.STAFF_RIGHTS_SETTINGS_CASHREGISTER]);
		
		ClientAppUtils.SetupFocusTraversal(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAdinfoLogo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelFiscalisation = new javax.swing.JPanel();
        jButtonFiscalisation = new javax.swing.JButton();
        jButtonEinvoice = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonPrinter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonExit = new javax.swing.JButton();
        jPanelAdminSettings = new javax.swing.JPanel();
        jButtonAdmin = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonLayout = new javax.swing.JButton();
        jButtonCashRegister = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButtonWorktime = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButtonPaymentMethods = new javax.swing.JButton();
        jButtonDiscounts = new javax.swing.JButton();
        jPanelTaxes = new javax.swing.JPanel();
        jButtonTaxRates = new javax.swing.JButton();
        jButtonConsumptionTaxes = new javax.swing.JButton();
        jLabelInternetConnection = new javax.swing.JLabel();
        jPanelImportSettings = new javax.swing.JPanel();
        jButtonImportSettings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Postavke");
        setResizable(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/adinfo/client/ui/adinfologo.jpg"))); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-2f));
        jLabel2.setText("mob: 095/6230-100");

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()-2f));
        jLabel3.setText("mob: 091/6230-670");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()-2f));
        jLabel4.setText("fax: 01/6230-699");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("tel: 01/6230-668");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()-2f));
        jLabel6.setText("office.accable@gmail.com");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAdinfoLogoLayout = new javax.swing.GroupLayout(jPanelAdinfoLogo);
        jPanelAdinfoLogo.setLayout(jPanelAdinfoLogoLayout);
        jPanelAdinfoLogoLayout.setHorizontalGroup(
            jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdinfoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelAdinfoLogoLayout.setVerticalGroup(
            jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdinfoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFiscalisation.setBorder(javax.swing.BorderFactory.createTitledBorder("Fiskalizacija i e-račun"));
        jPanelFiscalisation.setPreferredSize(new java.awt.Dimension(243, 143));

        jButtonFiscalisation.setText("<html> <div style=\"text-align: center\"> Fiskalizacija <br> [F]  </div> </html>");
        jButtonFiscalisation.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonFiscalisation.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonFiscalisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiscalisationActionPerformed(evt);
            }
        });

        jButtonEinvoice.setText("<html> <div style=\"text-align: center\"> E-račun <br> [E]  </div> </html>");
        jButtonEinvoice.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonEinvoice.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonEinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiscalisationLayout = new javax.swing.GroupLayout(jPanelFiscalisation);
        jPanelFiscalisation.setLayout(jPanelFiscalisationLayout);
        jPanelFiscalisationLayout.setHorizontalGroup(
            jPanelFiscalisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiscalisationLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonFiscalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonEinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelFiscalisationLayout.setVerticalGroup(
            jPanelFiscalisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiscalisationLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelFiscalisationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiscalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEinvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Printer"));
        jPanel2.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonPrinter.setText("<html> <div style=\"text-align: center\">  Printer <br> [P]  </div> </html>");
        jButtonPrinter.setToolTipText("");
        jButtonPrinter.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonPrinter.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrinterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonPrinter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Natrag"));
        jPanel4.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonExit.setText("<html> <div style=\"text-align: center\"> Natrag <br> [ESC]  </div> </html>");
        jButtonExit.setToolTipText("");
        jButtonExit.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonExit.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelAdminSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("Postavke Admin"));
        jPanelAdminSettings.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonAdmin.setText("<html> <div style=\"text-align: center\"> Postavke Admin <br> [A]  </div> </html>");
        jButtonAdmin.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonAdmin.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAdminSettingsLayout = new javax.swing.GroupLayout(jPanelAdminSettings);
        jPanelAdminSettings.setLayout(jPanelAdminSettingsLayout);
        jPanelAdminSettingsLayout.setHorizontalGroup(
            jPanelAdminSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminSettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelAdminSettingsLayout.setVerticalGroup(
            jPanelAdminSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdminSettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Kasa"));
        jPanel9.setPreferredSize(new java.awt.Dimension(243, 143));

        jButtonLayout.setText("<html> <div style=\"text-align: center\">  Touch screen <br> [R]  </div> </html>");
        jButtonLayout.setToolTipText("");
        jButtonLayout.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonLayout.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonLayout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayoutActionPerformed(evt);
            }
        });

        jButtonCashRegister.setText("<html> <div style=\"text-align: center\">  Postavke kase <br> [K]  </div> </html>");
        jButtonCashRegister.setToolTipText("");
        jButtonCashRegister.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonCashRegister.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonCashRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCashRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Radno vrijeme"));
        jPanel12.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonWorktime.setText("<html> <div style=\"text-align: center\">  Radno vrijeme <br> [D]  </div> </html>");
        jButtonWorktime.setToolTipText("");
        jButtonWorktime.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonWorktime.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonWorktime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWorktimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonWorktime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonWorktime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Plaćanje"));
        jPanel15.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonPaymentMethods.setText("<html> <div style=\"text-align: center\">  Načini plaćanja <br> [N]  </div> </html>");
        jButtonPaymentMethods.setToolTipText("");
        jButtonPaymentMethods.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonPaymentMethods.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonPaymentMethods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentMethodsActionPerformed(evt);
            }
        });

        jButtonDiscounts.setText("<html> <div style=\"text-align: center\">  Popusti <br> [U]  </div> </html>");
        jButtonDiscounts.setToolTipText("");
        jButtonDiscounts.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonDiscounts.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscountsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonPaymentMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPaymentMethods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelTaxes.setBorder(javax.swing.BorderFactory.createTitledBorder("Porez"));
        jPanelTaxes.setPreferredSize(new java.awt.Dimension(243, 143));

        jButtonTaxRates.setText("<html> <div style=\"text-align: center\"> Porezne stope <br> [Z]  </div> </html> ");
        jButtonTaxRates.setToolTipText("");
        jButtonTaxRates.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonTaxRates.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonTaxRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaxRatesActionPerformed(evt);
            }
        });

        jButtonConsumptionTaxes.setText("<html> <div style=\"text-align: center\"> Porez na potrošnju <br> [T]  </div> </html>");
        jButtonConsumptionTaxes.setToolTipText("");
        jButtonConsumptionTaxes.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonConsumptionTaxes.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonConsumptionTaxes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsumptionTaxesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTaxesLayout = new javax.swing.GroupLayout(jPanelTaxes);
        jPanelTaxes.setLayout(jPanelTaxesLayout);
        jPanelTaxesLayout.setHorizontalGroup(
            jPanelTaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaxesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonTaxRates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButtonConsumptionTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanelTaxesLayout.setVerticalGroup(
            jPanelTaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaxesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelTaxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTaxRates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsumptionTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabelInternetConnection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelInternetConnection.setForeground(new java.awt.Color(255, 0, 0));
        jLabelInternetConnection.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelInternetConnection.setText("NEMA INTERNETSKE VEZE");
        jLabelInternetConnection.setName("jLabelInternetConnection"); // NOI18N
        jLabelInternetConnection.setPreferredSize(new java.awt.Dimension(200, 20));

        jPanelImportSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("Učitaj postavke"));
        jPanelImportSettings.setPreferredSize(new java.awt.Dimension(133, 143));

        jButtonImportSettings.setText("<html> <div style=\"text-align: center\"> Učitaj <br> postavke <br> [L]  </div> </html>");
        jButtonImportSettings.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonImportSettings.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonImportSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelImportSettingsLayout = new javax.swing.GroupLayout(jPanelImportSettings);
        jPanelImportSettings.setLayout(jPanelImportSettingsLayout);
        jPanelImportSettingsLayout.setHorizontalGroup(
            jPanelImportSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImportSettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonImportSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelImportSettingsLayout.setVerticalGroup(
            jPanelImportSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImportSettingsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonImportSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelAdinfoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelInternetConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanelImportSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jPanelFiscalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelAdminSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAdinfoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelInternetConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelAdminSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelImportSettings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFiscalisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabelInternetConnection.setText("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
		Utils.DisposeDialog(this);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrinterActionPerformed
		new ClientAppSettingsPrinterDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonPrinterActionPerformed

    private void jButtonDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscountsActionPerformed
		new ClientAppSettingsDiscountsDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonDiscountsActionPerformed

    private void jButtonPaymentMethodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentMethodsActionPerformed
		new ClientAppPaymentMethodsDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonPaymentMethodsActionPerformed

    private void jButtonLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayoutActionPerformed
		new ClientAppSettingsLayoutDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonLayoutActionPerformed

    private void jButtonCashRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCashRegisterActionPerformed
		new ClientAppSettingsCashRegisterDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonCashRegisterActionPerformed

    private void jButtonWorktimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWorktimeActionPerformed
		new ClientAppSettingsWorktimeDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonWorktimeActionPerformed

    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
		new ClientAppSettingsAdminDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonAdminActionPerformed

    private void jButtonFiscalisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiscalisationActionPerformed
		new ClientAppSettingsFiscalisationDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonFiscalisationActionPerformed

    private void jButtonTaxRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaxRatesActionPerformed
		new ClientAppWarehouseTaxRatesDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonTaxRatesActionPerformed

    private void jButtonConsumptionTaxesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsumptionTaxesActionPerformed
		new ClientAppWarehouseConsumptionTaxesDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonConsumptionTaxesActionPerformed

    private void jButtonImportSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportSettingsActionPerformed
		new ClientAppSettingsImportSettingsDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonImportSettingsActionPerformed

    private void jButtonEinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinvoiceActionPerformed
		new ClientAppSettingsEinvoiceDialog(null, true).setVisible(true);
    }//GEN-LAST:event_jButtonEinvoiceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonCashRegister;
    private javax.swing.JButton jButtonConsumptionTaxes;
    private javax.swing.JButton jButtonDiscounts;
    private javax.swing.JButton jButtonEinvoice;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFiscalisation;
    private javax.swing.JButton jButtonImportSettings;
    private javax.swing.JButton jButtonLayout;
    private javax.swing.JButton jButtonPaymentMethods;
    private javax.swing.JButton jButtonPrinter;
    private javax.swing.JButton jButtonTaxRates;
    private javax.swing.JButton jButtonWorktime;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelInternetConnection;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAdinfoLogo;
    private javax.swing.JPanel jPanelAdminSettings;
    private javax.swing.JPanel jPanelFiscalisation;
    private javax.swing.JPanel jPanelImportSettings;
    private javax.swing.JPanel jPanelTaxes;
    // End of variables declaration//GEN-END:variables
}
