/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.client.ui.settings;

import hr.adinfo.client.ClientAppUtils;
import hr.adinfo.utils.Utils;
import hr.adinfo.utils.Values;
import hr.adinfo.utils.extensions.ColorIcon;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Window;
import java.awt.event.KeyEvent;

/**
 *
 * @author Matej
 */
public class ClientAppSettingsLayoutItemColorPickDialog extends javax.swing.JDialog {
	
	public boolean changeSuccess = false;
	public int finalItemColor = 0;
			
	/**
	 * Creates new form ClientAppWarehouseCategoriesAddDialog
	 */
	public ClientAppSettingsLayoutItemColorPickDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
				
		final Window thisWindow = this;
		KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
			@Override
			public boolean dispatchKeyEvent(KeyEvent ke) {
				if(!thisWindow.isDisplayable()){
					KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher(this);
				}
				
				if(!thisWindow.isFocused())
					return false;
				
				if(ke.getID() == KeyEvent.KEY_PRESSED){
					if(ke.getKeyCode() == KeyEvent.VK_ESCAPE){
						jButtonExit.doClick();
					}
				}
				
				return false;
			}
		});
		
		jButtonColor0.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[0], jButtonColor0.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor0.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor1.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[1], jButtonColor1.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor1.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor2.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[2], jButtonColor2.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor2.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor3.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[3], jButtonColor3.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor3.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor4.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[4], jButtonColor4.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor4.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor5.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[5], jButtonColor5.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor5.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor6.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[6], jButtonColor6.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor6.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor7.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[7], jButtonColor7.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor7.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor8.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[8], jButtonColor8.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor8.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor9.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[9], jButtonColor9.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor9.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor10.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[10], jButtonColor10.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor10.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		jButtonColor11.setIcon(new ColorIcon(Values.SETTINGS_LAYOUT_COLORS[11], jButtonColor11.getWidth() - Values.SETTINGS_LAYOUT_COLOR_OFFSET, jButtonColor11.getHeight() - Values.SETTINGS_LAYOUT_COLOR_OFFSET));
		
		ClientAppUtils.SetupFocusTraversal(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonColor0 = new javax.swing.JButton();
        jButtonColor1 = new javax.swing.JButton();
        jButtonColor2 = new javax.swing.JButton();
        jButtonColor3 = new javax.swing.JButton();
        jButtonColor4 = new javax.swing.JButton();
        jButtonColor5 = new javax.swing.JButton();
        jButtonColor6 = new javax.swing.JButton();
        jButtonColor7 = new javax.swing.JButton();
        jButtonColor8 = new javax.swing.JButton();
        jButtonColor9 = new javax.swing.JButton();
        jButtonColor10 = new javax.swing.JButton();
        jButtonColor11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Touch screen - uredi stavku");
        setResizable(false);

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Touch screen - odabir boje");
        jLabelTitle.setToolTipText("");

        jButtonExit.setText("<html> <div style=\"text-align: center\"> Odustani <br> [ESC] </div> </html>");
        jButtonExit.setPreferredSize(new java.awt.Dimension(84, 78));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Odabir boje"));

        jButtonColor0.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor0ActionPerformed(evt);
            }
        });

        jButtonColor1.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor1ActionPerformed(evt);
            }
        });

        jButtonColor2.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor2ActionPerformed(evt);
            }
        });

        jButtonColor3.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor3ActionPerformed(evt);
            }
        });

        jButtonColor4.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor4ActionPerformed(evt);
            }
        });

        jButtonColor5.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor5ActionPerformed(evt);
            }
        });

        jButtonColor6.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor6ActionPerformed(evt);
            }
        });

        jButtonColor7.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor7ActionPerformed(evt);
            }
        });

        jButtonColor8.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor8ActionPerformed(evt);
            }
        });

        jButtonColor9.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor9ActionPerformed(evt);
            }
        });

        jButtonColor10.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor10ActionPerformed(evt);
            }
        });

        jButtonColor11.setPreferredSize(new java.awt.Dimension(70, 70));
        jButtonColor11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColor11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButtonColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButtonColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButtonColor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButtonColor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jButtonColor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonColor0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonColor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
		Utils.DisposeDialog(this);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonColor0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor0ActionPerformed
		finalItemColor = 0;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor0ActionPerformed

    private void jButtonColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor1ActionPerformed
		finalItemColor = 1;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor1ActionPerformed

    private void jButtonColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor2ActionPerformed
		finalItemColor = 2;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor2ActionPerformed

    private void jButtonColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor3ActionPerformed
		finalItemColor = 3;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor3ActionPerformed

    private void jButtonColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor4ActionPerformed
		finalItemColor = 4;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor4ActionPerformed

    private void jButtonColor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor5ActionPerformed
		finalItemColor = 5;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor5ActionPerformed

    private void jButtonColor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor6ActionPerformed
		finalItemColor = 6;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor6ActionPerformed

    private void jButtonColor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor7ActionPerformed
		finalItemColor = 7;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor7ActionPerformed

    private void jButtonColor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor8ActionPerformed
		finalItemColor = 8;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor8ActionPerformed

    private void jButtonColor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor9ActionPerformed
		finalItemColor = 9;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor9ActionPerformed

    private void jButtonColor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor10ActionPerformed
        finalItemColor = 10;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor10ActionPerformed

    private void jButtonColor11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColor11ActionPerformed
        finalItemColor = 11;
		changeSuccess = true;
		jButtonExit.doClick();
    }//GEN-LAST:event_jButtonColor11ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonColor0;
    private javax.swing.JButton jButtonColor1;
    private javax.swing.JButton jButtonColor10;
    private javax.swing.JButton jButtonColor11;
    private javax.swing.JButton jButtonColor2;
    private javax.swing.JButton jButtonColor3;
    private javax.swing.JButton jButtonColor4;
    private javax.swing.JButton jButtonColor5;
    private javax.swing.JButton jButtonColor6;
    private javax.swing.JButton jButtonColor7;
    private javax.swing.JButton jButtonColor8;
    private javax.swing.JButton jButtonColor9;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
