/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.utils.database;

import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author Matej
 */
public class DatabaseQueryResult implements Serializable {
		private ArrayList<Object[]> data;
		private int counter;
		
		public int autoGeneratedKey = -1;
		
		public DatabaseQueryResult(){
			data = new ArrayList<>();
			counter = -1;
		}
		
		public boolean next(){
			++counter;
			return counter < data.size();
		}
		
		/** int column: the first column is 0, the second is 1, ... */
		public String getString(int column){
			if(counter < 0 || counter >= data.size())
				return null;
			
			if(column < 0 || column >= data.get(counter).length)
				return null;
			
			return String.valueOf(data.get(counter)[column]);
		}
		
		/** int column: the first column is 0, the second is 1, ... */
		public int getInt(int column){
			if(counter < 0 || counter >= data.size())
				return -1;
			
			if(column < 0 || column >= data.get(counter).length)
				return -1;
			
			int toReturn = -1;
			try {
				toReturn = Integer.parseInt(String.valueOf(data.get(counter)[column]));
			} catch (NumberFormatException ex) {}
			
			return toReturn;
		}
		
		/** int column: the first column is 0, the second is 1, ... */
		public float getFloat(int column){
			if(counter < 0 || counter >= data.size())
				return -1;
			
			if(column < 0 || column >= data.get(counter).length)
				return -1;
			
			float toReturn = -1;
			try {
				toReturn = Float.parseFloat(String.valueOf(data.get(counter)[column]));
			} catch (NumberFormatException ex) {}
			
			return toReturn;
		}
		
		/** int column: the first column is 0, the second is 1, ... */
		public byte[] getBytes(int column){
			if(counter < 0 || counter >= data.size())
				return null;
			
			if(column < 0 || column >= data.get(counter).length)
				return null;
			
			return (byte[]) data.get(counter)[column];
		}
		
		/** int column: the first column is 0, the second is 1, ... */
		public Object getObject(int column){
			if(counter < 0 || counter >= data.size())
				return null;
			
			if(column < 0 || column >= data.get(counter).length)
				return null;
			
			return data.get(counter)[column];
		}
		
		public void add(Object[] row){
			data.add(row);
		}
		
		public int getSize(){
			return data.size();
		}
	}