/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.utils.database;

import hr.adinfo.utils.Pair;
import static hr.adinfo.utils.Values.*;
import hr.adinfo.utils.communication.ServerQuery;
import java.io.Serializable;
import java.util.ArrayList;

/**
 *
 * @author Matej
 */
public class MultiDatabaseQuery extends ServerQuery implements Serializable {
	public int querySize;
	public String[] query;
	public ArrayList<Pair<Integer, String>>[] params;
	public ArrayList<Pair<Integer, byte[]>>[] paramsBytes;
	public Pair<Integer, String>[] autoIncrementParam;
	public String[] autoIncrementTable;
	public ArrayList<Pair<Integer, Integer>>[] autoGeneratedParams;
	public boolean executeLocally;
	
	public MultiDatabaseQuery(int querySize){
		super();
		this.querySize = querySize;
		query = new String[querySize];
		params = new ArrayList[querySize];
		paramsBytes = new ArrayList[querySize];
		autoIncrementParam = new Pair[querySize];
		autoIncrementTable = new String[querySize];
		autoGeneratedParams = new ArrayList[querySize];
		
		for(int i = 0; i < querySize; i++){
			params[i] = new ArrayList<>(0);
			paramsBytes[i] = new ArrayList<>(0);
			autoGeneratedParams[i] = new ArrayList<>(0);
		}
		timeoutSeconds = TIMEOUT_SELECT_QUERY_SECONDS;
	}
	
	public void SetQuery(int queryId, String value){
		query[queryId] = value;
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void AddParam(int queryId, int key, String value){
		params[queryId].add(new Pair<Integer, String>(key, value));
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void AddParam(int queryId, int key, int value){
		params[queryId].add(new Pair<Integer, String>(key, Integer.toString(value)));
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void AddParam(int queryId, int key, float value){
		params[queryId].add(new Pair<Integer, String>(key, Float.toString(value)));
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void AddParam(int queryId, int key, byte[] value){
		paramsBytes[queryId].add(new Pair<Integer, byte[]>(key, value));
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void SetAutoIncrementParam(int queryId, int key, String value, String table){
		autoIncrementParam[queryId] = new Pair<Integer, String>(key, value);
		autoIncrementTable[queryId] = table;
	}
	
	/** int key: the first parameter is 1, the second is 2, ... */
	public void AddAutoGeneratedParam(int queryId, int key, int generatedParamQueryId){
		autoGeneratedParams[queryId].add(new Pair<Integer, Integer>(key, generatedParamQueryId));
	}
}
