/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.control.ui;

import hr.adinfo.control.ControlAppLogger;
import hr.adinfo.control.ControlAppServerAppClient;
import hr.adinfo.utils.database.DatabaseQuery;
import hr.adinfo.utils.LoadingDialog;
import hr.adinfo.utils.communication.ServerResponse;
import static hr.adinfo.utils.Utils.DisposeDialog;
import static hr.adinfo.utils.Values.LICENCE_TYPE_CLIENT;
import static hr.adinfo.utils.Values.LICENCE_TYPE_LOCAL_SERVER;
import static hr.adinfo.utils.Values.LICENCE_TYPE_MASTER_LOCAL_SERVER;
import static hr.adinfo.utils.Values.RESPONSE_ERROR_CODE_SUCCESS;
import hr.adinfo.utils.database.DatabaseQueryResponse;
import hr.adinfo.utils.database.DatabaseQueryResult;
import hr.adinfo.utils.communication.ServerQueryTask;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.ExecutionException;
import javax.swing.JDialog;

/**
 *
 * @author Matej
 */
public class ControlAppEditLicenceDialog extends javax.swing.JDialog {

	int licenceId = -1;
	int officeId = -1;
	int userId = -1;
	
	/**
	 * Creates new form ControlAppEditLicenceWindow
	 */
	public ControlAppEditLicenceDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		jXDatePicker1.setFormats("dd.MM.yyyy");
		jXDatePicker1.getEditor().setEditable(false);
		jXDatePicker1.setDate(new Date());
	}
	
	public void SetData(int licenceId, String user, String office, String licenceType, String expirationDate, int officeId, int userId, String cashRegisterNumber){
		this.licenceId = licenceId;
		this.officeId = officeId;
		this.userId = userId;
		jLabelUser.setText(user);
		jLabelOffice.setText(office);
		jLabelCashRegisterNumber.setText(cashRegisterNumber);
		if("Blagajna".equals(licenceType)){
			jRadioButtonCashRegister.setSelected(true);
		} else if("Lokalni server".equals(licenceType)){
			jRadioButtonLocalServer.setSelected(true);
		} else {
			jRadioButtonMasterServer.setSelected(true);
		}

		try {
			Date date = new SimpleDateFormat("dd.MM.yyyy.").parse(expirationDate);
			jXDatePicker1.setDate(date);
		} catch (ParseException ex) {}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jButtonAdd = new javax.swing.JButton();
        jLabelUser = new javax.swing.JLabel();
        jLabelOffice = new javax.swing.JLabel();
        jRadioButtonCashRegister = new javax.swing.JRadioButton();
        jRadioButtonLocalServer = new javax.swing.JRadioButton();
        jRadioButtonMasterServer = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelCashRegisterNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Izmjena licence");

        jLabel2.setText("Korisnik:");

        jLabel3.setText("Poslovnica:");

        jLabel4.setText("Tip licence:");

        jLabel5.setText("Datum isteka:");

        jButtonAdd.setText("Spremi licencu");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelUser.setText("korisnik");

        jLabelOffice.setText("poslovnica");

        buttonGroup1.add(jRadioButtonCashRegister);
        jRadioButtonCashRegister.setSelected(true);
        jRadioButtonCashRegister.setText("Blagajna");

        buttonGroup1.add(jRadioButtonLocalServer);
        jRadioButtonLocalServer.setText("Lokalni server");

        buttonGroup1.add(jRadioButtonMasterServer);
        jRadioButtonMasterServer.setText("Glavni lokalni server");

        jLabel6.setText("Kasa broj:");

        jLabelCashRegisterNumber.setText("kasa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButtonAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOffice)
                            .addComponent(jLabelUser)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonCashRegister)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonLocalServer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMasterServer))
                            .addComponent(jLabelCashRegisterNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelUser))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelOffice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelCashRegisterNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonCashRegister)
                    .addComponent(jRadioButtonLocalServer)
                    .addComponent(jRadioButtonMasterServer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(licenceId == -1){
			ControlAppLogger.GetInstance().ShowMessage("licenceId == -1");
			DisposeDialog(this);
			return;
		}
		
		final int licenceType;
		if(jRadioButtonCashRegister.isSelected()){
			licenceType = LICENCE_TYPE_CLIENT;
		} else if(jRadioButtonLocalServer.isSelected()){
			licenceType = LICENCE_TYPE_LOCAL_SERVER;
		} else {
			licenceType = LICENCE_TYPE_MASTER_LOCAL_SERVER;
		}
		
		String expirationDate = jXDatePicker1.getEditor().getText().trim();
		
		// Check if LocalServer exist in Office, or MasterLocalServer exist in all Offices
		if(licenceType == LICENCE_TYPE_LOCAL_SERVER || licenceType == LICENCE_TYPE_MASTER_LOCAL_SERVER){
			final JDialog loadingDialog = new LoadingDialog(null, true);
			
			
			DatabaseQuery databaseQuery = new DatabaseQuery("SELECT ID FROM LICENCES WHERE OFFICE_ID = ? AND (TYPE = ? OR TYPE = ?) AND ID != ? FETCH FIRST ROW ONLY");
			databaseQuery.AddParam(1, officeId);
			databaseQuery.AddParam(2, LICENCE_TYPE_LOCAL_SERVER);
			databaseQuery.AddParam(3, LICENCE_TYPE_MASTER_LOCAL_SERVER);
			databaseQuery.AddParam(4, licenceId);
			ServerQueryTask databaseQueryTask = new ServerQueryTask(loadingDialog, databaseQuery, ControlAppServerAppClient.GetInstance(), ControlAppLogger.GetInstance());

			databaseQueryTask.execute();
			loadingDialog.setVisible(true);
			if(!databaseQueryTask.isDone()){
				databaseQueryTask.cancel(true);
				return;
			} else {
				try {
					ServerResponse serverResponse = databaseQueryTask.get();
					DatabaseQueryResult databaseQueryResult = null;
					if(serverResponse != null && serverResponse.errorCode == RESPONSE_ERROR_CODE_SUCCESS){
						databaseQueryResult = ((DatabaseQueryResponse) serverResponse).databaseQueryResult;
					}
					if(databaseQueryResult != null){
						if (databaseQueryResult.next()) {
							ControlAppLogger.GetInstance().ShowMessage("Lokalni server već postoji u ovoj poslovnici.");
							return;
						}
					} else {
						return;
					}
				} catch (InterruptedException | ExecutionException ex) {
					ControlAppLogger.GetInstance().ShowErrorLog(ex);
					return;
				}
			}
		}
		
		if(licenceType == LICENCE_TYPE_MASTER_LOCAL_SERVER){
			final JDialog loadingDialog = new LoadingDialog(null, true);
			
			
			String query = "SELECT OFFICES.USER_ID "
					+ "FROM (LICENCES INNER JOIN OFFICES ON LICENCES.OFFICE_ID = OFFICES.ID) "
					+ "WHERE OFFICES.USER_ID = ? AND LICENCES.TYPE = ? AND LICENCES.ID != ? "
					+ "FETCH FIRST ROW ONLY";
			DatabaseQuery databaseQuery = new DatabaseQuery(query);
			databaseQuery.AddParam(1, userId);
			databaseQuery.AddParam(2, LICENCE_TYPE_MASTER_LOCAL_SERVER);
			databaseQuery.AddParam(3, licenceId);
			ServerQueryTask databaseQueryTask = new ServerQueryTask(loadingDialog, databaseQuery, ControlAppServerAppClient.GetInstance(), ControlAppLogger.GetInstance());

			databaseQueryTask.execute();
			loadingDialog.setVisible(true);
			if(!databaseQueryTask.isDone()){
				databaseQueryTask.cancel(true);
				return;
			} else {
				try {
					ServerResponse serverResponse = databaseQueryTask.get();
					DatabaseQueryResult databaseQueryResult = null;
					if(serverResponse != null && serverResponse.errorCode == RESPONSE_ERROR_CODE_SUCCESS){
						databaseQueryResult = ((DatabaseQueryResponse) serverResponse).databaseQueryResult;
					}
					if(databaseQueryResult != null){
						if (databaseQueryResult.next()) {
							ControlAppLogger.GetInstance().ShowMessage("Glavni lokalni server već postoji kod ovog korisnika.");
							return;
						}
					} else {
						return;
					}
				} catch (InterruptedException | ExecutionException ex) {
					ControlAppLogger.GetInstance().ShowErrorLog(ex);
					return;
				}
			}
		}
		
		final JDialog loadingDialog = new LoadingDialog(null, true);
		
		
		DatabaseQuery databaseQuery = new DatabaseQuery("UPDATE LICENCES SET EXPIRATION_DATE = ?, TYPE = ? WHERE ID = ?");
		databaseQuery.AddParam(1, expirationDate);
		databaseQuery.AddParam(2, licenceType);
		databaseQuery.AddParam(3, licenceId);
		ServerQueryTask databaseQueryTask = new ServerQueryTask(loadingDialog, databaseQuery, ControlAppServerAppClient.GetInstance(), ControlAppLogger.GetInstance());
		
		databaseQueryTask.execute();
		loadingDialog.setVisible(true);
		if(!databaseQueryTask.isDone()){
			databaseQueryTask.cancel(true);
		} else {
			try {
				ServerResponse serverResponse = databaseQueryTask.get();
				DatabaseQueryResult databaseQueryResult = null;
				if(serverResponse != null && serverResponse.errorCode == RESPONSE_ERROR_CODE_SUCCESS){
					databaseQueryResult = ((DatabaseQueryResponse) serverResponse).databaseQueryResult;
				}
				if(databaseQueryResult != null){
					DisposeDialog(this);
				}
			} catch (Exception ex) {
				ControlAppLogger.GetInstance().ShowErrorLog(ex);
			}
		}
    }//GEN-LAST:event_jButtonAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCashRegisterNumber;
    private javax.swing.JLabel jLabelOffice;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JRadioButton jRadioButtonCashRegister;
    private javax.swing.JRadioButton jRadioButtonLocalServer;
    private javax.swing.JRadioButton jRadioButtonMasterServer;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
}
