/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.adinfo.client.ui;

import hr.adinfo.client.ClientApp;
import hr.adinfo.client.ClientAppLogger;
import hr.adinfo.client.ClientAppServerAppClient;
import hr.adinfo.utils.LoadingDialog;
import hr.adinfo.utils.Utils;
import hr.adinfo.utils.Values;
import hr.adinfo.utils.certificates.CertificateManager;
import hr.adinfo.utils.communication.ServerQueryTask;
import hr.adinfo.utils.communication.ServerResponse;
import hr.adinfo.utils.licence.Licence;
import hr.adinfo.utils.licence.LicenceQuery;
import hr.adinfo.utils.licence.LicenceQueryResponse;
import hr.adinfo.utils.licence.UniqueComputerID;
import hr.adinfo.utils.licence.UniqueComputerIdentifier;
import java.util.concurrent.ExecutionException;
import javax.swing.JDialog;

/**
 *
 * @author Matej
 */
public class ClientAppActivationWindow extends javax.swing.JFrame {

	/**
	 * Creates new form ClientAppActivationWindow
	 */
	public ClientAppActivationWindow() {
		initComponents();
		
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent windowEvent) {
				OnExit();
			}
		});
		
		jLabelId.setText("PCID: " + UniqueComputerID.GetUniqueID());
		String oldKey = Licence.GetActivationKey();
		if("".equals(oldKey)){
			jLabelOldActivationKey.setText("");
		} else {
			jLabelOldActivationKey.setText("Old activation key: " + oldKey);
		}
	}
	
	private void OnExit(){
		Utils.DisposeDialog(this);
		if(ClientApp.GetInstance() != null){
			ClientApp.GetInstance().OnAppClose();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonActivate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelOldActivationKey = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jPanelAdinfoLogo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jButtonActivate.setText("Aktiviraj");
        jButtonActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateActionPerformed(evt);
            }
        });

        jLabel1.setText("Unesite aktivacijski ključ:");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("(XXXX-XXXX-XXXX-XXXX)");

        jLabelOldActivationKey.setForeground(new java.awt.Color(102, 102, 102));
        jLabelOldActivationKey.setText("Old activation key: ");

        jLabelId.setForeground(new java.awt.Color(102, 102, 102));
        jLabelId.setText("PCID: ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hr/adinfo/client/ui/adinfologo.jpg"))); // NOI18N

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()-2f));
        jLabel3.setText("mob: 095/6230-100");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getSize()-2f));
        jLabel4.setText("mob: 091/6230-670");

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getSize()-2f));
        jLabel5.setText("fax: 01/6230-699");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()-2f));
        jLabel6.setText("tel: 01/6230-668");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()-2f));
        jLabel8.setText("office.accable@gmail.com");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAdinfoLogoLayout = new javax.swing.GroupLayout(jPanelAdinfoLogo);
        jPanelAdinfoLogo.setLayout(jPanelAdinfoLogoLayout);
        jPanelAdinfoLogoLayout.setHorizontalGroup(
            jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdinfoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanelAdinfoLogoLayout.setVerticalGroup(
            jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdinfoLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdinfoLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelOldActivationKey, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(361, 361, 361)
                                .addComponent(jButtonActivate))
                            .addComponent(jPanelAdinfoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelAdinfoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addComponent(jButtonActivate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jLabelOldActivationKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelId)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateActionPerformed
        String activationKey = jTextField1.getText().trim().toUpperCase();
		if(!activationKey.matches("\\w{4}-\\w{4}-\\w{4}-\\w{4}")){
			ClientAppLogger.GetInstance().ShowMessage("Molimo unesite aktivacijski ključ oblika XXXX-XXXX-XXXX-XXXX");
			return;
		}
		
		String uniqueId = UniqueComputerID.GetUniqueID();
		String message = activationKey + Values.LICENCE_SPLIT_STRING + uniqueId;
		
		final JDialog loadingDialog = new LoadingDialog(null, true);
		
		
		LicenceQuery licenceQuery = new LicenceQuery(Values.LICENCE_QUERY_ACTIVATE, message);
		ServerQueryTask serverQueryTask = new ServerQueryTask(loadingDialog, licenceQuery, ClientAppServerAppClient.GetInstance(), ClientAppLogger.GetInstance());

		serverQueryTask.execute();
		loadingDialog.setVisible(true);
		if(!serverQueryTask.isDone()){
			serverQueryTask.cancel(true);
		} else {
			try {
				ServerResponse serverResponse = serverQueryTask.get();
				byte[] publicKey = null;
				byte[] licence = null;
				int licenceErrorCode = -1;
				if(serverResponse != null && serverResponse.errorCode == Values.RESPONSE_ERROR_CODE_SUCCESS){
					publicKey = ((LicenceQueryResponse) serverResponse).publicKeyBytes;
					licence = ((LicenceQueryResponse) serverResponse).licenceBytes;
					licenceErrorCode = ((LicenceQueryResponse) serverResponse).licenceErrorCode;
				}
				if(licenceErrorCode == Values.LICENCE_ERROR_CODE_WRONG_CODE){
					ClientAppLogger.GetInstance().ShowMessage("Uneseni aktivacijski ključ je neispravan");
				} else if(licenceErrorCode == Values.LICENCE_ERROR_CODE_ALREADY_ACTIVE){
					ClientAppLogger.GetInstance().ShowMessage("Uneseni aktivacijski ključ je već aktiviran na drugom računalu");
				} else if(licenceErrorCode == Values.LICENCE_ERROR_CODE_ACTIVATION_SUCCESS && publicKey != null && licence != null){
					try {
						Licence.SavePublicKey(publicKey);
						Licence.SaveLicence(licence);
						Licence.SaveActivationKey(activationKey);
						CertificateManager.SaveCertificate(Values.CERT_DEMO_ROOT_ALIAS, ((LicenceQueryResponse) serverResponse).certDemoRootBytes);
						CertificateManager.SaveCertificate(Values.CERT_DEMO_SUB_ALIAS, ((LicenceQueryResponse) serverResponse).certDemoSubBytes);
						CertificateManager.SaveCertificate(Values.CERT_PROD_ROOT_ALIAS, ((LicenceQueryResponse) serverResponse).certProdRootBytes);
						CertificateManager.SaveCertificate(Values.CERT_PROD_SUB_ALIAS, ((LicenceQueryResponse) serverResponse).certProdSubBytes);
					} catch (Exception ex) {
						ClientAppLogger.GetInstance().ShowErrorLog(ex);
					}
					Utils.DisposeDialog(this);
					ClientApp.GetInstance().OnLicenceActivation();
				} else {
					ClientAppLogger.GetInstance().ShowMessage("Došlo je do pogreške kod aktivacije licence");
				}
			} catch (InterruptedException | ExecutionException ex) {
				ClientAppLogger.GetInstance().ShowErrorLog(ex);
			}
		}
    }//GEN-LAST:event_jButtonActivateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActivate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelOldActivationKey;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanelAdinfoLogo;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
